export const TARGETS = [
    // {
    //     project: "GRUDZDGOS",
    //     affectsVersions: ["2.14.0"],
    //     labels: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "MAINSTR",
    //     affectsVersions: ["3.8.0"],
    //     labels: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "RDKDOCSIS",
    //     affectsVersions: ["2.2.1"],
    //     labels: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "AIROHAOS",
    //     affectsVersions: ["1.3.1"],
    //     labels: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "GENXPON",
    //     affectsVersions: ["5.0.0"],
    //     labels: ["GEN10", "SFR", "GR140OH"],
    //     components: ["WebGUI"],
    //     stripBrackets: true,
    // },
    // {
    //     project: "GRUDZDGOS",
    //     affectsVersions: ["2.13.1"],
    //     labels: ["WebGUI"],
    //     client: ["HOT"],
    // },
    // {
    //     project: "MAINSTR",
    //     affectsVersions: ["3.7.2"],
    //     labels: ["WebGUI"],
    //     client: ["HOT"],
    // },
    // {
    //     project: "RDKDOCSIS",
    //     affectsVersions: ["2.2.3"],
    //     labels: ["WebGUI"],
    //     client: ["HOT"],
    // },
    // {
    //     project: "GENXPON",
    //     affectsVersions: ["5.0.0"],
    //     labels: ["GEN10", "HOT", "XSR140LNR"],
    //     components: ["WebGUI"],
    //     stripBrackets: true,
    // },
    // {
    //     project: "GRUDZDGOS",
    //     affectsVersions: ["2.9.2"],
    //     labels: ["WebGUI"],
    //     client: ["MEO"],
    // },
    // {
    //     project: "MAINSTR",
    //     affectsVersions: ["3.3.0"],
    //     labels: ["WebGUI"],
    //     client: ["MEO"],
    // },
    // {
    //     project: "GENXPON",
    //     affectsVersions: ["5.0.0"],
    //     labels: ["GEN10", "MEO", "XSR240LNR"],
    //     components: ["WebGUI"],
    //     stripBrackets: true,
    // },
    // {
    //     project: "GENXPON",
    //     affectsVersions: ["5.0.0"],
    //     labels: ["GEN10", "MEO", "GR240NHR"],
    //     components: ["WebGUI"],
    //     stripBrackets: true,
    // },
    // {
    //     project: "MAINSTR",
    //     affectsVersions: ["3.7.1"],
    //     labels: ["WebGUI"],
    //     client: ["MSS", "AIN", "TEL"],
    // },
    // {
    //     project: "NBWEBTI",
    //     affectsVersions: ["5.1.0"],
    //     labels: ["WebGUI"],
    //     client: ["FGWSFR,FGWMEO,FGWHOT,FGWMSS,FGWTEL,FGWAIN,DOCSISSFR,DOCSISHOT,FGWELSFR"],
    // },
];