export const TARGETS = [
    // {
    //     project: "GRUDZDGOS",
    //     affectsVersions: ["2.8.3"],
    //     labels: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "MAINSTR",
    //     affectsVersions: ["3.2.3"],
    //     labels: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "RDKDOCSIS",
    //     affectsVersions: ["2.2.1"],
    //     labels: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "AIROHAOS",
    //     affectsVersions: ["1.3.1"],
    //     labels: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "GENXPON",
    //     affectsVersions: ["5.0.0"],
    //     labels: ["GEN10", "SFR", "XSR140LNR"],
    //     components: ["WebGUI"],
    //     client: ["SFR"],
    // },
    // {
    //     project: "GRUDZDGOS",
    //     affectsVersions: ["2.13.0"],
    //     labels: ["WebGUI"],
    //     client: ["HOT"],
    // },
    // {
    //     project: "MAINSTR",
    //     affectsVersions: ["3.7.0"],
    //     labels: ["WebGUI"],
    //     client: ["HOT"],
    // },
    // {
    //     project: "RDKDOCSIS",
    //     affectsVersions: ["2.2.3"],
    //     labels: ["WebGUI"],
    //     client: ["HOT"],
    // },
    // {
    //     project: "GENXPON",
    //     affectsVersions: ["5.0.0"],
    //     labels: ["GEN10", "HOT", "XSR140LNR"],
    //     components: ["WebGUI"],
    //     client: ["HOT"],
    // },
    // {
    //     project: "GRUDZDGOS",
    //     affectsVersions: ["2.9.2"],
    //     labels: ["WebGUI"],
    //     client: ["MEO"],
    // },
    // {
    //     project: "MAINSTR",
    //     affectsVersions: ["3.3.0"],
    //     labels: ["WebGUI"],
    //     client: ["MEO"],
    // },
    // {
    //     project: "GENXPON",
    //     affectsVersions: ["5.0.0"],
    //     labels: ["GEN10", "MEO", "XSR240LNR"],
    //     components: ["WebGUI"],
    //     client: ["MEO"],
    // },
    // {
    //     project: "GENXPON",
    //     affectsVersions: ["5.0.0"],
    //     labels: ["GEN10", "MEO", "GR240NHR"],
    //     components: ["WebGUI"],
    //     client: ["MEO"],
    // },
    // {
    //     project: "MAINSTR",
    //     affectsVersions: ["3.7.1"],
    //     labels: ["WebGUI"],
    //     client: ["MSS"],
    // },
    {
        project: "NBWEBTI",
        affectsVersions: ["4.0.2"],
        client: ["DOCSISHOT"],
    },
];